import { Project } from './project';

export const PROJECTS: Project[] = [
    {
        id: 1,
        slug: 'comugraph',
        name: 'Comugraph',
        url: 'https://www.comugraph.dk/',
        description: 'Comugraph is a Web based project for Design Company. I developed the WordPress based website based on the design provided by the Company as I acknowledge their design capibilities.',
        primaryColor: '#FFE500',
        secondaryColor: '#FFF7AE',
        imageUrl: '../../assets/img/comugraph.png',
        titleOne: 'Carefully crafted experience',
        textOne: 'In cooperation with Comugraph we made sure that the experience served is the best based on the screen size and device. We made that happen by using device testing while adjusting the content over several iterations to deliver the best experiences on each screen.',
        imageUrlOne: '../../assets/img/responsive-comu.png',
        titleTwo: 'Custom interactions',
        textTwo: 'As the project was done for design company it was important to focus on user experience. To improve it I decided to use animations creating smoother experience of transitions. Revealing the content in the specific moment to viewer also helped  to deliver better  user experience.',
        imageUrlTwo: '../../assets/img/animations.jpg',
        titleThree: 'Interactions mosaic',
        textThree: 'As the result of this project by creating connection between all the small pices of animations and interaction I managed deliver an experiance that is consistent on the entire website.',
        imageUrlThree: '../../assets/img/mosaic.png',
    },
    {
        id: 2,
        slug: 'wavey',
        name: 'Wavey',
        url: 'https://www.wavey.dk/',
        description: 'Wavey is website focused on articles for Music Jurnalists. In this project I was responsible for both the UI/UX and development of the Website.',
        primaryColor: '#F700FF',
        secondaryColor: '#FBBAFE',
        imageUrl: '../../assets/img/wavey.png',
        titleOne: '',
        textOne: '',
        imageUrlOne: '',
        titleTwo: '',
        textTwo: '',
        imageUrlTwo: '',
        titleThree: '',
        textThree: '',
        imageUrlThree: '',
    },
    {
        id: 3,
        slug: 'federiconicole',
        name: 'Federiconicole',
        url: 'https://www.federiconicole.it/',
        description: '',
        imageUrl: '../../assets/img/federiconicole.png',
        primaryColor: '#ED7465',
        secondaryColor: '#F2C3BE',
        titleOne: '',
        textOne: '',
        imageUrlOne: '',
        titleTwo: '',
        textTwo: '',
        imageUrlTwo: '',
        titleThree: '',
        textThree: '',
        imageUrlThree: '',
    },
];