import { Project } from './project';

export const PROJECTS: Project[] = [
    {
        id: 1,
        slug: 'comugraph',
        name: 'Comugraph',
        url: 'https://www.comugraph.dk/',
        description: 'Comugraph is a Web based project for Design Company. I developed the WordPress based website based on the design provided by the Company as I acknowledge their design capibilities.',
        primaryColor: '#FFE500',
        secondaryColor: '#FFF7AE',
        imageUrl: '../../assets/img/comugraph.png',
        titleOne: 'Carefully crafted experience',
        textOne: 'In cooperation with Comugraph we made sure that the experience served is the best based on the screen size and device. We made that happen by using device testing while adjusting the content over several iterations to deliver the best experiences on each screen.',
        imageUrlOne: '../../assets/img/responsive-comugraph.png',
        titleTwo: 'Custom interactions',
        textTwo: 'As the project was done for design company it was important to focus on user experience. To improve it I decided to use animations creating smoother experience of transitions. Revealing the content in the specific moment to viewer also helped  to deliver better  user experience.',
        imageUrlTwo: '../../assets/img/animations.gif',
        titleThree: 'Interactions mosaic',
        textThree: 'As the result of this project by creating connection between all the small pices of animations and interaction I managed deliver an experiance that is consistent on the entire website.',
        imageUrlThree: '../../assets/img/mosaic.png',
    },
    {
        id: 2,
        slug: 'wavey',
        name: 'Wavey',
        url: 'https://www.wavey.dk/',
        description: 'Wavey is website focused on articles for Music Jurnalists. In this project I was responsible for both the UI/UX and development of the Website.',
        primaryColor: '#F700FF',
        secondaryColor: '#FBBAFE',
        imageUrl: '../../assets/img/wavey.png',
        titleOne: 'Customer driven visualisation',
        textOne: 'In this project I got the customer deeply involved in the creation process. By his presence throughtout mockup and visualisation phase I ensured that the result is meeting his goals.',
        imageUrlOne: '../../assets/img/customer.png',
        titleTwo: 'Content Heavy',
        textTwo: 'This Website main focus are articles so I decided to use the WordPress CMS. As this CMS was mainly design for blogs and text heavy sites.',
        imageUrlTwo: '../../assets/img/heavy.png',
        titleThree: 'Navigation consistency',
        textThree: 'The most interesting part of this project was composing all the navigation elements into consistent whole. It was challenging as the present parts of navigation were based on the device.',
        imageUrlThree: '../../assets/img/navigation.png',
    },
    {
        id: 3,
        slug: 'federiconicole',
        name: 'Federiconicole',
        url: 'https://www.federiconicole.it/',
        description: 'Federiconicole is a wedding website made for a friend. It was a personal project where I was resposible for all from comunication to realisation.',
        imageUrl: '../../assets/img/federiconicole.png',
        primaryColor: '#ED7465',
        secondaryColor: '#F2C3BE',
        titleOne: 'Communication with customer',
        textOne: 'In this project direct communication with customer have enabled me to influance the direction of it. That helped me deliver the project that would meet their expectations.',
        imageUrlOne: '../../assets/img/com.jpg',
        titleTwo: 'Visaulisation and Development',
        textTwo: 'Federiconicole was place where I could connect my graphical and programic skills. During the visaulisation phase I was considering the development challenges which helped me deliver the project before deadline.',
        imageUrlTwo: '../../assets/img/devVis.png',
        titleThree: 'Connecting feedback and user knowledge',
        textThree: 'Combining the feedback from the customer and my knowladge made it possible to create project meeting the user Goal. Which in this case was helping the guests find the way and prepare for Wedding.',
        imageUrlThree: '../../assets/img/feedback.jpg',
    },
];